config/routes.rb
Rails.application.routes.draw do
  resources :administradors
  resources :pedidos
  resources :clientes
  root "clientes#index"
  get "/login", to: "login#index"
  post "/login", to: "login#login"
  get "/sair", to: "login#sair"
  get "/esqueci-senha", to: "login#esqueci"
  post "/recuperar", to: "login#recuperar"
  get "/troca-senha", to: "login#troca_senha"
  post "/altera-senha", to: "login#altera_senha"
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :pedidos #, dependent: :destroy

    validates :nome, :telefone, presence: true

    validates :telefone, format: { with: /\A\(\d{2}\) \d{5}-\d{4}\z/, message: "deve ter o formato (99) 99999-9999" }

    validates :nome, length: { minimum: 5, maximum: 20 }

    validates :cpf, uniqueness: { allow_nil: true, allow_blank: true }

    validates :cnpj, uniqueness: { allow_nil: true, allow_blank: true }

    validates :cpf, format: { with: /\A\d{3}\.\d{3}\.\d{3}-\d{2}\z/, allow_blank: true, message: "deve ter o formato XXX.XXX.XXX-XX" }

    validates :cnpj, format: { with: /\A\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}\z/, allow_blank: true, message: "deve ter o formato XX.XXX.XXX/XXXX-XX" }

    # validates :endereco, numericality: true
    # validates :endereco, numericality: { greater_than: 0 }
    # validates :endereco, numericality: { greater_than_or_equal_to: 0 }
    # validates :endereco, numericality: { less_than: 0 }
    # validates :endereco, numericality: { less_than_or_equal_to: 0 }

    # validates :endereco, inclusion: { in: ["São Paulo", "Rio de Janeiro", "Belo Horizonte"] }
    # validates :endereco, exclusion: { in: ["Otário", "otário", "otario", "otário", "filho da puta"] }
    validate :nao_pode_palavras_de_baixo_calao, :palavras_maiusculas

    def nao_pode_palavras_de_baixo_calao
        if self.endereco.downcase.scan(/otário|otario|filho da puta/).present?
            self.errors.add(:base, "não pode palavras de baixo calão")
        end
    end

    def palavras_maiusculas
        if self.endereco.upcase != self.endereco
            self.errors.add(:base, "Não está tudo maiúsculo")
        end
    end

    def self.find(id)
        obj = super(id)
        return obj if obj.ativo

        raise "Cliente Inativo"
    end

    def destroy
        Cliente.where(id: self.id).update_all(ativo: false)
    end

    def delete
        self.destroy
    end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all.limit(10).order("id desc")
    @quantidade_de_cientes = TamanhoDoRelatorio.descobrir_o_tamanho
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy!

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :telefone, :endereco, :cpf, :cnpj)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">
  <p>
    <strong>Nome:</strong>
    <%= cliente.nome %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= cliente.telefone %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= cliente.endereco %>
  </p>

</div>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2>Confira os erros abaixo</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :cnpj, style: "display: block" %>
    <%= form.text_field :cnpj %>
  </div>

  <div>
    <%= form.label :endereco, style: "display: block" %>
    <%= form.text_area :endereco %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Show this cliente", @cliente %> |
  <%= link_to "Back to clientes", clientes_path %>
</div>

app/views/clientes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes - Quantidade de clientes <%= @quantidade_de_cientes %></h1>

<div id="clientes">
  <% @clientes.each do |cliente| %>
    <%= render cliente %>
    <p>
      <%= link_to "Show this cliente", cliente %>
    </p>
  <% end %>
</div>

<%= link_to "New cliente", new_cliente_path, class: "btn btn-primary" %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Back to clientes", clientes_path %>
</div>

app/views/clientes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cliente %>

<div>
  <%= link_to "Edit this cliente", edit_cliente_path(@cliente) %> |
  <%= link_to "Back to clientes", clientes_path %>

  <%= button_to "Destroy this cliente", @cliente, method: :delete %>
</div>