config/routes.rb
Rails.application.routes.draw do
  resources :administradors
  resources :pedidos
  resources :clientes
  root "clientes#index"
  get "/login", to: "login#index"
  post "/login", to: "login#login"
  get "/sair", to: "login#sair"
  get "/esqueci-senha", to: "login#esqueci"
  post "/recuperar", to: "login#recuperar"
  get "/troca-senha", to: "login#troca_senha"
  post "/altera-senha", to: "login#altera_senha"
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  # self.table_name = "tbl_pedidos"
  # self.primary_key = 'id_pedido'
  belongs_to :cliente

  has_many :produtos, foreign_key: "id_do_pedido"

end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]

  # GET /pedidos or /pedidos.json
  def index
    @pedidos = Pedido.all.includes(:cliente).limit(10)
    # @pedidos = Pedido.all.includes(:cliente).joins(:cliente).limit(10)
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos or /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    @pedido.destroy!

    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: "Pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:cliente_id, :valor_total, :itens)
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido) do |form| %>
  <% if pedido.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cliente_id, style: "display: block" %>
    <%= form.text_field :cliente_id %>
  </div>

  <div>
    <%= form.label :valor_total, style: "display: block" %>
    <%= form.text_field :valor_total %>
  </div>

  <div>
    <%= form.label :itens, style: "display: block" %>
    <%= form.text_area :itens %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pedidos/_pedido.html.erb
<div id="<%= dom_id pedido %>">
  <p>
    <strong>Cliente:</strong>
    <%= pedido.cliente_id %>
  </p>

  <p>
    <strong>Valor total:</strong>
    <%= pedido.valor_total %>
  </p>

  <p>
    <strong>Itens:</strong>
    <%= pedido.itens %>
  </p>

</div>

app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Show this pedido", @pedido %> |
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

app/views/pedidos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pedidos</h1>

<div id="pedidos" class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Cliente</th>
        <th scope="col">Valor Total</th>
        <th scope="col">Itens</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @pedidos.each do |pedido| %>
        <tr>
          <th scope="row"><%= pedido.id %></th>
          <td><%= pedido.cliente.nome %></td>
          <td><%= number_to_currency(pedido.valor_total) %></td>
          <td><%= pedido.itens %></td>
          <td>
            <%= link_to "Show this pedido", pedido, class: "btn btn-primary btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New pedido", new_pedido_path, class: "btn btn-success" %>

app/views/pedidos/new.html.erb
<h1>New pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

app/views/pedidos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pedido %>

<div>
  <%= link_to "Edit this pedido", edit_pedido_path(@pedido) %> |
  <%= link_to "Back to pedidos", pedidos_path %>

  <%= button_to "Destroy this pedido", @pedido, method: :delete %>
</div>